# POST http://localhost:5000/user/register
# Content-Type: application/json
 
# {
#   "username": "Amber",
#   "password": "amb123",
#   "role": "STUDENT",
#   "fullName": "Amber Drew",
#   "contactNumber": "7896540321",
#   "email": "amber@gmail.com",
#   "address": "Winston",
#   "dateOfBirth": "2000-05-05",
#   "subject": "maths",
#   "yearsOfExperience": 29
# }
 
# POST http://localhost:5000/user/login
# Content-Type: application/json
 
# {
#   "username": "Amber",
#   "password": "amb123"
# }
 
 //getting 
# GET http://localhost:5000/user/1
 


 //Getting student - details
# GET http://localhost:5000/student
# Authorization: Bearer 
# Content-Type: application/json