POST http://localhost:5000/user/register
Content-Type: application/json

{
    "username": "teach2",
    "password": "Teacher1",
    "role": "TEACHER",
    "fullName": "Teacher Sample A",
    "contactNumber": "9087654321",
    "email": "teacher2@gmail.com",
    "subject": "CS",
    "yearsOfExperience": 3
}
###
//Register - Student
POST http://localhost:5000/user/register
Content-Type: application/json

{
    "username": "student1",
    "password": "Student1",
    "role": "STUDENT",
    "fullName": "Student Sample A",
    "contactNumber": "9807654321",
    "email": "student1@gmail.com",
    "address": "25 Park Street, Kolkata, West Bengal, 700016",
    "dateOfBirth": "2002-08-21"
}
###
// Teacher Login
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "username": "teach2",
    "password": "Teacher1"
}
###
// Student Login
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "username": "student1",
    "password": "Student1"
}


###
//Add Course
POST http://localhost:5000/course
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiVEVBQ0hFUiIsInVzZXJJZCI6MSwiaWF0IjoxNzYxMDUyMzExLCJleHAiOjE3NjExMzg3MTF9.knfytK8bCVRhiVRXn6eeu9w34MVtLLPeL-nuWfAkP1fYBIURBGn1HDFngZUXiXmd9877KiPIQ5UaDfwlUcdatw
Content-Type: application/json

{
    "courseName":"Differential",
    "description":"Differentiation",
    "teacher":{
        "teacher_id":1
    }
}

###
//Get all courses
GET http://localhost:5000/course
Authorization: Bearer  eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiVEVBQ0hFUiIsInVzZXJJZCI6NCwiaWF0IjoxNzYxMTA5NDkzLCJleHAiOjE3NjExOTU4OTN9.IGaJPK91fioSpUJ_1WbWcwQUj9qqXubYrPTJiRXLLjm64KtDxL65o_kjO2Hx3ugs18SzSI2s7q2Lcb09dewFSw
Content-Type: application/json

###
//Get course by Id
GET http://localhost:5000/course/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiVEVBQ0hFUiIsInVzZXJJZCI6MSwiaWF0IjoxNzYxMDUyMzExLCJleHAiOjE3NjExMzg3MTF9.knfytK8bCVRhiVRXn6eeu9w34MVtLLPeL-nuWfAkP1fYBIURBGn1HDFngZUXiXmd9877KiPIQ5UaDfwlUcdatw
Content-Type: application/json

###
// Get courses by Teacher by id
GET http://localhost:5000/course/teacher/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiVEVBQ0hFUiIsInVzZXJJZCI6NCwiaWF0IjoxNzYxMTA5NDkzLCJleHAiOjE3NjExOTU4OTN9.IGaJPK91fioSpUJ_1WbWcwQUj9qqXubYrPTJiRXLLjm64KtDxL65o_kjO2Hx3ugs18SzSI2s7q2Lcb09dewFSw
Content-Type: application/json

###
//Get all students
GET http://localhost:5000/student
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiVEVBQ0hFUiIsInVzZXJJZCI6MSwiaWF0IjoxNzYxMDUyMzExLCJleHAiOjE3NjExMzg3MTF9.knfytK8bCVRhiVRXn6eeu9w34MVtLLPeL-nuWfAkP1fYBIURBGn1HDFngZUXiXmd9877KiPIQ5UaDfwlUcdatw
Content-Type: application/json

###
//Get student by id
GET http://localhost:5000/student/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiVEVBQ0hFUiIsInVzZXJJZCI6MSwiaWF0IjoxNzYxMDUyMzExLCJleHAiOjE3NjExMzg3MTF9.knfytK8bCVRhiVRXn6eeu9w34MVtLLPeL-nuWfAkP1fYBIURBGn1HDFngZUXiXmd9877KiPIQ5UaDfwlUcdatw
Content-Type: application/json

###
//Get all teachers
GET http://localhost:5000/teacher
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiVEVBQ0hFUiIsInVzZXJJZCI6NCwiaWF0IjoxNzYxMTA5NDkzLCJleHAiOjE3NjExOTU4OTN9.IGaJPK91fioSpUJ_1WbWcwQUj9qqXubYrPTJiRXLLjm64KtDxL65o_kjO2Hx3ugs18SzSI2s7q2Lcb09dewFSw
Content-Type: application/json

###
//Get teacher by id
GET http://localhost:5000/teacher/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiVEVBQ0hFUiIsInVzZXJJZCI6MSwiaWF0IjoxNzYxMDUyMzExLCJleHAiOjE3NjExMzg3MTF9.knfytK8bCVRhiVRXn6eeu9w34MVtLLPeL-nuWfAkP1fYBIURBGn1HDFngZUXiXmd9877KiPIQ5UaDfwlUcdatw
Content-Type: application/json

###
//Get teacher by yearsofExperience (sorted order)
GET http://localhost:5000/teacher/yearsofexperience
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiVEVBQ0hFUiIsInVzZXJJZCI6NCwiaWF0IjoxNzYxMTA5NDkzLCJleHAiOjE3NjExOTU4OTN9.IGaJPK91fioSpUJ_1WbWcwQUj9qqXubYrPTJiRXLLjm64KtDxL65o_kjO2Hx3ugs18SzSI2s7q2Lcb09dewFSw
Content-Type: application/json





###
//Add course
POST http://localhost:5000/course
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiVEVBQ0hFUiIsInVzZXJJZCI6MiwiaWF0IjoxNzYxMDQ2NTMxLCJleHAiOjE3NjExMzI5MzF9.L4wh76uEAbG8ykKJcC-iKVKDXGWAsXtSk5QNBOVRcAutMmc3EUMQIzcxn973k7vT6-ae8ktBO6vBPG8aXOBcTg
Content-Type: application/json


{
    "courseName": "DS",
    "description": "Data Structures",
    "teacher" : {
        "teacherId":2
    }
}

###
//Add enrollment
POST http://localhost:5000/enrollment
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiVEVBQ0hFUiIsInVzZXJJZCI6MiwiaWF0IjoxNzYxMDQ2NTMxLCJleHAiOjE3NjExMzI5MzF9.L4wh76uEAbG8ykKJcC-iKVKDXGWAsXtSk5QNBOVRcAutMmc3EUMQIzcxn973k7vT6-ae8ktBO6vBPG8aXOBcTg
Content-Type: application/json

{
    "student":{
        "studentId":1
    },
    "course":{
        "courseId":1
    },
    "enrollmentDate":"2025-02-01"
}

###
//Get all enrollments
GET http://localhost:5000/enrollment
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiVEVBQ0hFUiIsInVzZXJJZCI6NCwiaWF0IjoxNzYxMTA5NDkzLCJleHAiOjE3NjExOTU4OTN9.IGaJPK91fioSpUJ_1WbWcwQUj9qqXubYrPTJiRXLLjm64KtDxL65o_kjO2Hx3ugs18SzSI2s7q2Lcb09dewFSw
Content-Type: application/json

###
///delete  teacher by id
DELETE  http://localhost:5000/teacher/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiVEVBQ0hFUiIsInVzZXJJZCI6MSwiaWF0IjoxNzYxMDQ1NjgwLCJleHAiOjE3NjExMzIwODB9.sO8vv76_zodTxNAhEzeVBUH4htQVRsEeMpuvvYyWi115sB15UMDFD1X2JPt9U19gYkE0fhelen5fS0wo8_UVGA
Content-Type: application/json